---
- hosts: all
  sudo: true
  vars_files:
    - vars/{{envn}}/common.yml
  tags: ['debug']

- hosts: mysql
  sudo: true
  vars_files:
    - vars/{{envn}}/common.yml
    - vars/{{envn}}/mysql.yml
  roles:
    - ANXS.mysql
  tags: ['mysql']

- hosts: lls
  sudo: true
  vars_files:
    - vars/{{envn}}/common.yml
    - vars/{{envn}}/ruby.yml
    - vars/{{envn}}/lls.yml
  roles:
    - geerlingguy.ruby
    - lls.app
  tags: ['lls']
